[tool.pyright]
include = [
    "roles/importer/files/importer",
]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    ".git",
    ".venv",
    "venv",
    "scripts",
    "roles/importer/files/importer/test",
]

ignore = [
    "./scripts",
]

venvPath = "."
venv = ".venv"

typeCheckingMode = "strict"
reportMissingImports = false
reportMissingTypeStubs = true



[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "__init__.py",
    "scripts",
    "roles/tests-integration",
    "roles/importer/files/importer/test"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN",     # flake8-annotations: Type annotation checks
    "COM",     # flake8-commas: Trailing comma checks
    "C90",     # mccabe: Complexity checks
    "DJ",      # flake8-django: Django-specific checks
    "EXE",     # flake8-executable: Executable file checks
    "T10",     # flake8-debugger: Debugger import checks
    "TID",     # flake8-tidy-imports: Import organization checks
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "D106",    # Missing docstring in public nested class
    "D107",    # Missing docstring in __init__
    "D200",    # One-line docstring should fit on one line
    "D203",    # 1 blank line required before class docstring
    "D205",    # 1 blank line required between summary line and description
    "D212",    # Multi-line docstring summary should start at the first line
    "D400",    # First line should end with a period
    "D401",    # First line should be in imperative mood
    "D415",    # First line should end with a period, question mark, or exclamation point
    "D417",    # Missing argument descriptions in the docstring
    "E402",    # Module level import not at top of file
    "E501",    # Line too long
    "TRY003",  # Avoid specifying long messages outside the exception class
    "TD002",   # Missing author in TODO
    "TD003",   # Missing issue link on the line following a TODO
    "FIX002",  # Line contains TODO, consider resolving the issue
    "EM101",   # Exception must not use a string literal, assign to variable first
    "EM102",   # Exception must not use an f-string literal, assign to variable first
    "PTH100",  # os.path.abspath() should be replaced by Path.resolve()
    "PTH123",  # open() should be replaced by Path.open()
    "PLR0913", # Too many arguments in function definition
    "PT009",   # Use a regular assert instead of unittest-style assertEqual
    "PLR0915", # Too many statements
    "PLR0912", # Too many branches
    "PLR0911", # Too many return statements
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "BLE001",  # Do not catch blind exception: Exception
    "DTZ005",  # datetime.datetime.now() called without a tz argument
    "TRY301",  # Abstract raise to an inner function
    "TRY300",  # Consider moving this statement to an else block
    "B904",    # Within an except clause, raise exceptions with raise ... from err
    "S113",    # Probable use of requests call without timeout
    "S104",    # Possible binding to all interfaces
]
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


