- block:

    - set_fact: distribution_version="{{ ansible_facts['distribution_major_version'] }}"    
      when: ansible_facts['distribution']|lower == 'debian'

    - set_fact: distribution_version="{{ ansible_facts['distribution_version'] }}"    
      when: ansible_facts['distribution']|lower == 'ubuntu'

    - set_fact: distribution_version="11"    
      when: ansible_facts['distribution']|lower == 'debian' and ansible_facts['distribution_major_version'] == 'testing'

    # for all distros except ubuntu >=22.04 we need to include a package source
    - block:

      - name: get package list from ms {{ dotnet_deb_name }}
        get_url:
          url: "https://packages.microsoft.com/config/{{ ansible_facts['distribution']|lower }}/{{ distribution_version }}/{{ dotnet_deb_name }}"
          dest: "{{ middleware_server_base_dir }}/{{ dotnet_deb_name }}"
          mode: "0644"

      - name: install ms package list
        apt:
          deb: "{{ middleware_server_base_dir }}/{{ dotnet_deb_name }}"

      - name: remove package list file
        file:
          dest: "{{ middleware_server_base_dir }}/{{ dotnet_deb_name }}"
          state: absent

      - name: apt update
        apt: update_cache=true

      when: ansible_facts['distribution']|lower != 'ubuntu' or ansible_facts['distribution_major_version'] is version('22', '<'))

    - name: Install apt-transport-https
      package: name=apt-transport-https state=present

    - name: apt update
      apt: update_cache=true

    - name: Install dotnet-sdk-{{ dotnet_version }}
      package: "name=dotnet-sdk-{{ dotnet_version }} state=present"

    - name: copy middleware server systemd service script
      template:
        src: fworch-middleware.service.j2
        dest: "/lib/systemd/system/{{ middleware_service_name }}.service"
        backup: yes
        mode: "0644"
        owner: "root"

  become: yes
  environment: "{{ proxy_env }}"

- name: publish middlewareserver
  command: "dotnet publish --no-self-contained -c {{ dotnet_mode }} -o {{ middleware_server_start_dir }}/bin/{{ dotnet_mode }}/net{{ dotnet_version }}"
  args:
    chdir: "{{ middleware_server_start_dir }}"
  become: yes
  become_user: "{{ fworch_user }}"
  environment: "{{ proxy_env }}"

- name: make middleware service run at host startup
  systemd:
    name: "{{ middleware_service_name }}"
    enabled: yes
  become: yes

  # not starting the server as the api is not ready yet
  # we will restart the middlewareserver later 
