- block:

    - name: copy blazor ui systemd service script
      template:
        src: fworch-blazor-ui.service.j2
        dest: "/lib/systemd/system/{{ ui_service_name }}.service"
        backup: true
        mode: "0644"
        owner: "root"
      register: ui_service_template

  become: true
  environment: "{{ proxy_env }}"

- name: track ui deployment changes from systemd template
  set_fact:
    ui_deploy_changed: "{{ (ui_deploy_changed | default(false)) or ui_service_template.changed }}"

- name: publish blazor ui
  command: "dotnet publish --no-self-contained -c {{ dotnet_mode }} -o {{ ui_start_dir }}/bin/{{ dotnet_mode }}/net{{ dotnet_version }}"
  args:
    chdir: "{{ ui_start_dir }}"
  become: true
  become_user: "{{ fworch_user }}"
  environment: "{{ proxy_env }}"
  register: publish_result
  when: ui_deploy_changed | default(false)

- name: fail if publish returned an error
  fail:
    msg: "could not publish ui server successfully: {{ publish_result }}"
  when: publish_result is defined and publish_result.rc != 0

- name: make blazor ui run at host startup
  systemd:
    name: "{{ ui_service_name }}"
    enabled: true
  become: true

- name: start blazor ui
  systemd:
    name: "{{ ui_service_name }}"
    state: restarted
    daemon_reload: true
  become: true
  when: ui_deploy_changed | default(false)
