
- block:

  - name: creating {{ fworch_db_name }}-db-model
    postgresql_query:
      db: "{{ fworch_db_name }}"
      path_to_script: "{{ database_install_dir }}/sql/creation/{{ item }}"
    loop:
      - fworch-create-tables.sql
      - fworch-create-constraints.sql
      - fworch-create-foreign-keys.sql
      - fworch-create-indices.sql
      - fworch-fill-stm.sql
    when: installation_mode == "new"

  become: yes
  become_user: postgres
