
- name: (re)defines functions and views (idempotent)
  postgresql_query:
    db: "{{ fworch_db_name }}"
    path_to_script: "{{ database_install_dir }}/sql/idempotent/{{ item }}"
    as_single_query: "{{ postgresql_query_as_single_query }}"
  become: yes
  become_user: postgres
  when: ansible_version.string is version_compare('2.10', '>=')
  loop:
    - fworch-basic-procs.sql
    - fworch-import.sql
    - fworch-import-main.sql
    - fworch-obj-import.sql
    - fworch-obj-refs.sql
    - fworch-svc-import.sql
    - fworch-svc-refs.sql
    - fworch-usr-import.sql
    - fworch-usr-refs.sql
    - fworch-rule-import.sql
    - fworch-rule-refs.sql
    - fworch-rule-resolved.sql
    - fworch-zone-import.sql
    - fworch-report.sql
    - fworch-qa.sql
    - fworch-report-basics.sql
    - fworch-views.sql
    - fworch-api-funcs.sql
    - fworch-grants.sql

- name: (re)defines functions and views (idempotent)
  postgresql_query:
    db: "{{ fworch_db_name }}"
    path_to_script: "{{ database_install_dir }}/sql/idempotent/{{ item }}"
  become: yes
  become_user: postgres
  when: ansible_version.string is version_compare('2.10', '<')
  loop:
    - fworch-basic-procs.sql
    - fworch-import.sql
    - fworch-import-main.sql
    - fworch-obj-import.sql
    - fworch-obj-refs.sql
    - fworch-svc-import.sql
    - fworch-svc-refs.sql
    - fworch-usr-import.sql
    - fworch-usr-refs.sql
    - fworch-rule-import.sql
    - fworch-rule-refs.sql
    - fworch-rule-resolved.sql
    - fworch-zone-import.sql
    - fworch-report.sql
    - fworch-qa.sql
    - fworch-report-basics.sql
    - fworch-views.sql
    - fworch-api-funcs.sql
    - fworch-grants.sql
