---
- name: delete test user cred config file
  file:
    path: "{{ fworch_secrets_dir }}/TestUserCreds.json"
    state: absent
  become: true
  listen: "test importer handler"

- block:
  - name: delete test checkpoint R8x credentials cascading to deletion of mgmt and gw 
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: >
        DO $do$ BEGIN 
        DELETE FROM import_credential WHERE credential_name='{{ test_credential_name }}'; 
        END $do$ 
    listen: "test importer handler"

  - name: delete tenants tenant1_test and tenant2_test
    postgresql_query:
      db: "{{ fworch_db_name }}"
      query: >
        DO $do$ BEGIN 
        DELETE FROM tenant WHERE tenant_name='tenant1{{ test_postfix }}' OR tenant_name='tenant2{{ test_postfix }}'; 
        END $do$
    listen: "test importer handler"

  become: true
  become_user: postgres

- name: build ldap tls options
  set_fact:
    ldap_tls_opts: >-
      {% if openldap_server_enable_ssl | default(false) -%}
      -o TLS_REQCERT=never{% if openldap_server_cert is defined %} -o TLS_CACERT={{ openldap_server_cert }}{% endif %}
      {%- endif %}
    ldap_cmd_port: >-
      {% if openldap_server_enable_ssl | default(false) -%}
      {{ openldap_port | default(636) }}
      {%- else -%}
      {{ (openldap_port | default(389) | int == 636) | ternary(389, openldap_port | default(389)) }}
      {%- endif %}
    ldap_cmd_url: >-
      {{ (openldap_server_enable_ssl | default(false)) | ternary('ldaps', 'ldap') }}://{{ openldap_server }}:{{ ldap_cmd_port }}
  listen: "test importer handler"

- name: find ldap entries with test_postfix
  command: "ldapsearch {{ ldap_tls_opts }} -H {{ ldap_cmd_url }} -D {{ openldap_superuser_dn }} -y {{ ldap_manager_pwd_file }} -b {{ openldap_path }} -x '(|(cn=*{{ sample_postfix }}*)(ou=*{{ sample_postfix }}*)(uid=*{{ sample_postfix }}*))'"
  register: ldap_entries_to_delete
  listen: "test importer handler"
  become: true

- set_fact:
    delete_list: "{{ ldap_entries_to_delete.stdout | replace('\n', '') }}"
  listen: "test importer handler"

- set_fact:
    delete_list2: "{{ delete_list.split('dn: ')[1:] | sort(reverse = True) }}"
  listen: "test importer handler"

- name: delete ldap test data
  command: "ldapdelete {{ ldap_tls_opts }} -H {{ ldap_cmd_url }} -D {{ openldap_superuser_dn }} -y {{ ldap_manager_pwd_file }} -x {{ item | regex_replace('\\s', '') | regex_replace('dc=internal.*', 'dc=internal') }}"
  listen: "test importer handler"
  loop: "{{ delete_list2 }}"
  become: true
