
# - name: stop old middleware server
#   systemd:
#     name: "{{ middleware_service_name }}"
#     enabled: false
#     status: stopped
#   become: true

# - name: remove debugging middleware server
#   file:
#     path: "/usr/local/fworch/middleware/files/FWO.Middleware.Server/bin/Debug"
#     state: absent
#   become: true
