### general settings
product_version: "5.7.1"
ansible_become: yes
ansible_user: "{{ lookup('env', 'USER') }}"
ansible_become_method: sudo
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
product_name: fworch

### host information
ui_server: "{{ groups['frontends'].0 }}" #todo: this could be more then one
middleware_server: "{{ groups['middlewareserver'].0 }}"
log_server: "{{ groups['logserver'].0 }}"
databaseserver_server: "{{ groups['databaseserver'].0 }}"
importer_server: "{{ groups['importers'].0 }}" #todo: this could be more then one
api_server: "{{ groups['apiserver'].0 }}"

ui_hostname: "{{ hostvars[ui_server]['ansible_facts']['fqdn'] }}"
middleware_hostname: "{{ hostvars[middleware_server]['ansible_facts']['fqdn'] }}"
syslog_host: "{{ hostvars[log_server]['ansible_facts']['fqdn'] }}"
fworch_db_host: "{{ hostvars[databaseserver_server]['ansible_facts']['fqdn'] }}"
importer_hostname: "{{ hostvars[importer_server]['ansible_facts']['fqdn'] }}"
api_hostname: "{{ hostvars[api_server]['ansible_facts']['fqdn'] }}"

# installation_mode options:
#   new (default) - assumes that no fworch is installed on the target devices - fails if it finds an installation
#   uninstall     - runs uninstall-fworch.yml
#   upgrade       - installs on top of an existing system preserving any existing data in ldap, database, api
installation_mode: new
install_syslog: true
run_on_github: false
add_demo_data: true
api_docu: false
# initialize upgrade files list to empty, needed when running in test only mode (-t test):
upgrade_files: []

### operating system settings
user_id: 60320
fworch_user: "{{ product_name }}"
fworch_group: "{{ fworch_user }}"
fworch_parent_dir: "/usr/local"
fworch_home: "{{ fworch_parent_dir }}/{{ product_name }}"
fworchtest_user: "{{ product_name }}test"
fworchtest_home: "/home/{{ fworchtest_user }}"
fworch_conf_dir: "{{ fworch_home }}/etc"
fworch_conf_file: "{{ fworch_conf_dir }}/fworch.json"
fworch_secrets_dir: "{{ fworch_conf_dir }}/secrets"

# setting default proxy (may be overwritten via --extra-vars)
http_proxy: "{{ lookup('env','http_proxy') }}"
https_proxy: "{{ lookup('env','https_proxy') }}"
proxy_exceptions: "{{ lookup('env','no_proxy') }}"
proxy_env:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        HTTP_PROXY: "{{ http_proxy }}"
        HTTPS_PROXY: "{{ https_proxy }}"
        no_proxy: "{{ proxy_exceptions }}"

http_proxy_import_parameter: ""
# proxy in capitals needed for debian and ubuntu <20
# use the following syntax for authenticated proxy access:
# http_proxy=http://USERNAME:PASSWORD@1.2.3.4:8080/

test_packages:
  - postgresql-client
  - curl
server_admin: "root@{{ api_hostname }}"
arch: x86_64
redhat_major_version: "8"
redhat_arch: "{{ redhat_major_version }}-{{ arch }}"

### database stuff
fworch_db_port: 5432
fworch_db_name: fworchdb
fworch_dbadmin_name: dbadmin
dbadmin_password_file: "{{ fworch_secrets_dir }}/dbadmin_pwd"
fworch_db_password_file: "{{ fworch_secrets_dir }}/fworch_db_pwd"

### middleware server 
jwt_private_key_file: "{{ fworch_secrets_dir }}/jwt_private_key.pem"
jwt_public_key_file: "{{ fworch_secrets_dir }}/jwt_public_key.pem"
ldap_manager_pwd_file: "{{ fworch_secrets_dir }}/ldap_manager_pwd"

ldif_changetype: add
middleware_service_name: "{{ product_name }}-middleware"


# middleware web server
middleware_web_listener_port: 8888
middleware_uri: "https://{{ middleware_hostname }}:{{ middleware_web_listener_port }}/"
##### application server data
middleware_internal_port: 8880
# currently not used: web_server_name: "{{ middleware_hostname }}"

ui_admin_password_file: "{{ fworch_secrets_dir }}/ui_admin_pwd"
ui_admin_testonly_password: "fworch.1"

### database & api
api_service_name: fworch-hasura-docker-api
api_container_name: "{{ product_name }}-api"
api_web_port: 9443
api_hasura_jwt_alg: "RS256"
api_hasura_jwt_secret: "fake-jwt-secret-for-github-install"
api_uri: "https://{{ api_hostname }}:{{ api_web_port }}/api/v1/graphql"

### dotnet
dotnet_deb_name: "packages-microsoft-prod.deb"
dotnet_version: "6.0"
dotnet_mode: "Release"
# dotnet_mode: "Debug"
debug_level: "1"
lib_dir: "{{ fworch_home }}/lib/files"

### password generation
randomly_generated_pwd: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

### logging
syslog_proto: tcp
syslog_port: 514
middleware_server_syslog_id: "{{ product_name }}.middleware-server"
ui_syslog_id: "{{ product_name }}-ui"
ldap_syslog_id: slapd
api_log_level: info

### apache: both package and dir name (needed both on ui and api hosts):
webserver_package_name: apache2
http_conf_dir: /etc/{{ webserver_package_name }}/sites-available/
wsgi_package_name: libapache2-mod-wsgi

################# testing #########################
test_dir: "{{ fworch_home }}/test"
test_fortigate_name: "fortigate{{ test_postfix }}"
test_checkpoint_name: "checkpoint{{ test_postfix }}"
csharp_test_start_dir: "{{ fworch_home }}/test/csharp/FWO.Test"
