
# hasura:
api_port: 8080
### high timeout value for api (mainly) for large imports (4h)
apache_fwo_api_timeout: 14400
api_user: "{{ fworch_dbadmin_name }}"
api_hasura_admin_test_password: "not4production"
api_user_email: "{{ api_user }}@{{ api_ip_address }}"
api_home: "{{ fworch_home }}/api"
api_hasura_cli_bin: "{{ fworch_home }}/api/bin/hasura"
api_hasura_version: "v2.14.0"
api_project_name: api
api_no_metadata: false
api_rollback_is_running: false
# debug > info > warn > error
api_HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, websocket-log"
# api_HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, websocket-log, query-log"
api_HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: true
