
ui_port: 5000
ui_web_port: 443
ui_app_name: "{{ product_name }}"
ui_dir: "{{ fworch_home }}/ui/files"
ui_start_dir: "{{ ui_dir }}/FWO.UI"
ui_admin_password_file: "{{ fworch_secrets_dir }}/ui_admin_pwd"
# ui_comm_mode valid values: 
# standard (meaning with http-->https rewrite and websockets), no_ws, allow_http, no_ws_and_allow_http
ui_comm_mode: standard

# correct name for demo installation:
ui_server_name: fworch-test-server
# further aliases:
ui_server_alias: fwodemo.cactus.de

ui_php_dir: "{{ fworch_home }}/web/htdocs"
ui_php_web_port: 8443
ui_service_name: "{{ product_name }}-ui"

apache_ui_timeout: 14400
