
sample_config_user: fworchsample
sample_config_user_home: "/home/{{ sample_config_user }}"
import_sample_server: localhost
sample_config_hostname: isosrv #todo: delete? not used anywhere
importer_hostname: localhost 
sample_data_rate: medium
sample_role_purpose: demo
sample_fortigate_name: fortigate_demo
sample_checkpoint_name: "dummy only relevant for testing"
sample_postfix: _demo

# sample openldap server
second_ldap_db: no
sample_ldap_path: "dc=example,dc=com"
sample_ldap_domain_name: example.com
sample_ldap_superuser_name: "cn=Manager,ou=user,{{ sample_ldap_path }}"
