
sample_config_user: fworchsample
sample_config_user_home: "/home/{{ sample_config_user }}"
import_sample_server: localhost
sample_config_hostname: isosrv
importer_hostname: localhost
sting_ip: "192.168.100.110"
sting_port: "443"
sample-data-rate: medium

# sample openldap server
second_ldap_db: no
sample_ldap_path: "dc=example,dc=com"
sample_ldap_domain_name: example.com
sample_ldap_superuser_name: "cn=Manager,ou=user,{{ sample_ldap_path }}"
