
sample_config_user: fworchsample
# sample_config_user_home: "/home/{{ sample_config_user }}"
sample_data_rate: medium
sample_role_purpose: demo
sample_fortigate_basename: fortigate
sample_fortigate_name: "{{ sample_fortigate_basename }}_demo"
sample_checkpoint_basename: "checkpoint"
sample_checkpoint_name: "{{ sample_checkpoint_basename }}_demo"
sample_checkpoint_uri: "https://fwodemodata.cactus.de/demo04_cpr8x.json"
demo_cpr8x_name_without_demo: "CPR81"
demo_cpr8x_name: "{{ demo_cpr8x_name_without_demo}}_demo"
demo_cpr8x_uri: "https://fwodemodata.cactus.de/demo09_cpr81.json"
demo_fos_name_without_demo: "FortiOS"
demo_fos_name: "{{ demo_fos_name_without_demo }}_demo"
demo_fos_uri: "https://fwodemodata.cactus.de/demo10_fOS.json"
sample_postfix: _demo

# sample openldap server
second_ldap_db: no
sample_ldap_path: "dc=example,dc=com"
sample_ldap_domain_name: example.com
sample_ldap_superuser_name: "cn=Manager,ou=user,{{ sample_ldap_path }}"
